{% set name = "dtaidistance" %}
{% set version = "1.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/wannesm/dtaidistance.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python=3.8
    - numpy
  run:
    - python=3.8
    - numpy

test:
  imports:
    - dtaidistance
